'use strict'

require('dotenv').config()

const fs = require('fs')
const path = require('path')
const readline = require('readline')
const chalk = require('chalk')
const inquirer = require('inquirer')
const db = require('./db')
const { route, getProviderList } = require('./router')
const logger = require('./logger')

// ── setup ──────────────────────────────────────────────────────

async function setup () {
  console.log(chalk.bold('\n  AI Router — First Time Setup\n'))
  console.log(chalk.gray('  Your API keys will be saved to .env on your machine.'))
  console.log(chalk.gray('  They are never committed to GitHub.\n'))

  const envPath = path.join(process.cwd(), '.env')
  const existing = {}

  // Read existing .env if it exists
  if (fs.existsSync(envPath)) {
    const lines = fs.readFileSync(envPath, 'utf8').split('\n')
    for (const line of lines) {
      const [key, ...rest] = line.split('=')
      if (key && rest.length) existing[key.trim()] = rest.join('=').trim()
    }
  }

  const answers = await inquirer.prompt([
    {
      type: 'password',
      name: 'GEMINI_API_KEY',
      message: 'Gemini API key (free at aistudio.google.com):',
      default: existing.GEMINI_API_KEY || '',
      mask: '*'
    },
    {
      type: 'password',
      name: 'GROQ_API_KEY',
      message: 'Groq API key (free at console.groq.com):',
      default: existing.GROQ_API_KEY || '',
      mask: '*'
    },
    {
      type: 'password',
      name: 'ANTHROPIC_API_KEY',
      message: 'Anthropic API key (optional, press Enter to skip):',
      default: existing.ANTHROPIC_API_KEY || '',
      mask: '*'
    },
    {
      type: 'password',
      name: 'OPENAI_API_KEY',
      message: 'OpenAI API key (optional, press Enter to skip):',
      default: existing.OPENAI_API_KEY || '',
      mask: '*'
    }
  ])

  // Build .env content
  const envLines = [
    '# AI Router — generated by ai-router setup',
    `# Updated: ${new Date().toISOString()}`,
    '',
    `GEMINI_API_KEY=${answers.GEMINI_API_KEY}`,
    `GROQ_API_KEY=${answers.GROQ_API_KEY}`,
    `ANTHROPIC_API_KEY=${answers.ANTHROPIC_API_KEY}`,
    `OPENAI_API_KEY=${answers.OPENAI_API_KEY}`,
    '',
    'PORT=3000',
    'SLIDING_WINDOW_SIZE=10',
    'LOG_LEVEL=info'
  ]

  fs.writeFileSync(envPath, envLines.join('\n') + '\n')

  console.log(chalk.green('\n  ✓ API keys saved to .env'))
  console.log(chalk.gray('  Run: ai-router chat to start a session\n'))
}

// ── chat ───────────────────────────────────────────────────────

async function chat () {
  // Get or create a session
  let sessionId = db.getLatestSession()
  if (!sessionId) {
    sessionId = db.createSession()
    logger.info(`New session created: ${sessionId}`)
  }

  // Build system prompt from memory
  const memory = db.getAllMemory()
  const systemPrompt = buildSystemPrompt(memory)

  console.log(chalk.bold('\n  AI Router — Chat\n'))
  console.log(chalk.gray('  Type your message and press Enter.'))
  console.log(chalk.gray('  Type /new to start a new session.'))
  console.log(chalk.gray('  Type /status to see all provider states.'))
  console.log(chalk.gray('  Type /exit or press Ctrl+C to quit.\n'))

  // Show which providers are ready
  const providers = getProviderList()
  const ready = providers.filter(p => p.status === 'ready' && p.configured)
  if (ready.length === 0) {
    console.log(chalk.red('  No providers configured. Run: ai-router setup\n'))
    return
  }
  console.log(chalk.gray(`  Providers ready: ${ready.map(p => p.name).join(', ')}\n`))

  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  })

  const askQuestion = () => {
    rl.question(chalk.cyan('  You: '), async (input) => {
      const message = input.trim()

      if (!message) {
        askQuestion()
        return
      }

      if (message === '/exit') {
        console.log(chalk.gray('\n  Goodbye.\n'))
        rl.close()
        db.closeDb()
        return
      }

      if (message === '/new') {
        sessionId = db.createSession()
        console.log(chalk.gray(`\n  New session started.\n`))
        askQuestion()
        return
      }

      if (message === '/status') {
        showProviderStatus()
        askQuestion()
        return
      }

      try {
        process.stdout.write(chalk.gray('  Thinking...'))
        const result = await route(sessionId, message, systemPrompt)
        process.stdout.clearLine(0)
        process.stdout.cursorTo(0)

        console.log(chalk.bold(`\n  ${result.provider}:`))
        console.log(`  ${result.text.split('\n').join('\n  ')}`)
        console.log(chalk.gray(`\n  [${result.provider}]\n`))

      } catch (err) {
        process.stdout.clearLine(0)
        process.stdout.cursorTo(0)
        console.log(chalk.red(`\n  Error: ${err.message}\n`))
        logger.error(err.message)
      }

      askQuestion()
    })
  }

  askQuestion()
}

// ── providers ──────────────────────────────────────────────────

function providers () {
  const list = getProviderList()

  console.log(chalk.bold('\n  AI Router — Provider Status\n'))

  for (const p of list) {
    const statusColor = p.status === 'ready' ? chalk.green
      : p.status === 'not configured' ? chalk.gray
      : chalk.yellow

    console.log(`  ${chalk.bold(p.name.padEnd(16))} ${statusColor(p.status)}`)

    if (p.configured) {
      console.log(chalk.gray(`  ${''.padEnd(16)} Requests: ${p.totalRequests}  Tokens: ${p.totalTokens}`))
    }

    if (p.lastError) {
      console.log(chalk.gray(`  ${''.padEnd(16)} Last error: ${p.lastError}`))
    }

    console.log()
  }
}

// ── history ────────────────────────────────────────────────────

function history () {
  const messages = db.getHistory(20)

  if (messages.length === 0) {
    console.log(chalk.gray('\n  No history yet. Start a chat with: ai-router chat\n'))
    return
  }

  console.log(chalk.bold('\n  AI Router — Recent History\n'))

  for (const msg of [...messages].reverse()) {
    const roleLabel = msg.role === 'user'
      ? chalk.cyan('  You')
      : chalk.bold(`  ${msg.provider_used}`)

    const time = msg.created_at.slice(0, 16)
    console.log(`${roleLabel} ${chalk.gray(time)}`)
    const preview = msg.content.slice(0, 120)
    console.log(`  ${preview}${msg.content.length > 120 ? '...' : ''}`)
    console.log()
  }
}

// ── memory ─────────────────────────────────────────────────────

function memoryShow () {
  const mem = db.getAllMemory()
  const keys = Object.keys(mem)

  console.log(chalk.bold('\n  AI Router — Stored Memory\n'))

  if (keys.length === 0) {
    console.log(chalk.gray('  No memory stored yet.'))
    console.log(chalk.gray('  Set a preference with: ai-router memory set <key> <value>'))
    console.log(chalk.gray('  Example: ai-router memory set language Hindi\n'))
    return
  }

  for (const key of keys) {
    console.log(`  ${chalk.bold(key.padEnd(20))} ${mem[key]}`)
  }
  console.log()
}

function memorySet (key, value) {
  if (!key || !value) {
    console.log(chalk.red('\n  Usage: ai-router memory set <key> <value>'))
    console.log(chalk.gray('  Example: ai-router memory set tone casual\n'))
    return
  }

  db.setMemory(key, value)
  console.log(chalk.green(`\n  ✓ Memory updated: ${key} = ${value}\n`))
  logger.info(`Memory set: ${key} = ${value}`)
}

function memoryDelete (key) {
  if (!key) {
    console.log(chalk.red('\n  Usage: ai-router memory delete <key>\n'))
    return
  }

  db.deleteMemory(key)
  console.log(chalk.green(`\n  ✓ Memory deleted: ${key}\n`))
}

// ── In-chat provider status ────────────────────────────────────

function showProviderStatus () {
  const list = getProviderList()

  console.log(chalk.bold('\n  Provider Status\n'))

  for (const p of list) {
    // Status label + color
    let statusLabel
    let statusColor

    if (!p.configured) {
      statusLabel = 'not configured — add key with: ai-router setup'
      statusColor = chalk.gray
    } else if (p.status.startsWith('cooling down')) {
      statusLabel = `on cooldown — ${p.status.match(/\d+s/)?.[0] || '60s'} remaining (hit rate limit)`
      statusColor = chalk.yellow
    } else if (p.lastError) {
      // Shorten long SDK error messages to the useful part
      const shortError = shortenError(p.lastError)
      statusLabel = `last error — ${shortError}`
      statusColor = chalk.red
    } else {
      statusLabel = 'ready'
      statusColor = chalk.green
    }

    console.log(`  ${chalk.bold(p.name.padEnd(16))} ${statusColor(statusLabel)}`)

    if (p.configured && p.totalRequests > 0) {
      console.log(
        chalk.gray(`  ${''.padEnd(16)} ${p.totalRequests} requests · ${p.totalTokens.toLocaleString()} tokens used this session`)
      )
    }

    console.log()
  }
}

function shortenError (errorMsg) {
  // Extract just the meaningful part from long SDK error strings
  if (errorMsg.includes('404')) return 'model not found — name may have changed'
  if (errorMsg.includes('401') || errorMsg.toLowerCase().includes('api key')) return 'invalid API key — run: ai-router setup'
  if (errorMsg.includes('429') || errorMsg.toLowerCase().includes('rate limit')) return 'rate limit hit'
  if (errorMsg.includes('402') || errorMsg.toLowerCase().includes('quota')) return 'quota exceeded'
  if (errorMsg.toLowerCase().includes('decommissioned')) return 'model decommissioned — update model name'
  if (errorMsg.toLowerCase().includes('not found')) return 'model not found — name may have changed'
  // Return first 80 chars of anything else
  return errorMsg.slice(0, 80)
}

// ── System prompt builder ──────────────────────────────────────

function buildSystemPrompt (memory) {
  const lines = [
    'You are a helpful AI assistant continuing an ongoing conversation.',
    'The conversation history below is ground truth — treat it as your own prior responses.',
    'Do not mention which AI model you are unless directly asked.'
  ]

  if (Object.keys(memory).length > 0) {
    lines.push('\nUser preferences (always respect these):')
    for (const [key, value] of Object.entries(memory)) {
      lines.push(`- ${key}: ${value}`)
    }
  }

  return lines.join('\n')
}

module.exports = {
  setup,
  chat,
  providers,
  history,
  memoryShow,
  memorySet,
  memoryDelete
}