'use strict'

const fs   = require('fs')
const path = require('path')
const os   = require('os')

// All user data lives in ~/.ai-router/ — package files are never touched
const HOME_DIR    = path.join(os.homedir(), '.ai-router')
const CONFIG_FILE = path.join(HOME_DIR, 'config.json')
const ENV_FILE    = path.join(HOME_DIR, '.env')
const DB_FILE     = path.join(HOME_DIR, 'memory.db')
const LOGS_DIR    = path.join(HOME_DIR, 'logs')
const GRAPHS_DIR  = path.join(HOME_DIR, 'graphs')
const VENV_DIR    = path.join(HOME_DIR, 'venv')

// Default config shape — written on first run
const DEFAULT_CONFIG = {
  version: '0.5.0',
  providers: [],          // user's configured providers
  sequences: {},          // priority sequences per context type
  caps: {},               // token caps per provider
  created_at: new Date().toISOString()
}

// ── Home directory setup ───────────────────────────────────────

function ensureHomeDir () {
  if (!fs.existsSync(HOME_DIR))    fs.mkdirSync(HOME_DIR,    { recursive: true })
  if (!fs.existsSync(LOGS_DIR))    fs.mkdirSync(LOGS_DIR,    { recursive: true })
  if (!fs.existsSync(GRAPHS_DIR))  fs.mkdirSync(GRAPHS_DIR,  { recursive: true })

  if (!fs.existsSync(CONFIG_FILE)) {
    fs.writeFileSync(CONFIG_FILE, JSON.stringify(DEFAULT_CONFIG, null, 2))
  }

  if (!fs.existsSync(ENV_FILE)) {
    fs.writeFileSync(ENV_FILE, '# AI Router API Keys\n# Generated by ai-router setup\n')
  }
}

// ── Config read / write ────────────────────────────────────────

function readConfig () {
  ensureHomeDir()
  try {
    return JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf8'))
  } catch {
    return { ...DEFAULT_CONFIG }
  }
}

function writeConfig (config) {
  ensureHomeDir()
  config.updated_at = new Date().toISOString()
  fs.writeFileSync(CONFIG_FILE, JSON.stringify(config, null, 2))
}

// ── Provider management ────────────────────────────────────────

function getProviders () {
  return readConfig().providers || []
}

function addProvider (provider) {
  const config = readConfig()
  const existing = config.providers.findIndex(p => p.name === provider.name)
  if (existing >= 0) {
    config.providers[existing] = provider
  } else {
    config.providers.push(provider)
  }
  writeConfig(config)
}

function removeProvider (name) {
  const config = readConfig()
  config.providers = config.providers.filter(p => p.name !== name)
  writeConfig(config)
}

function getProvider (name) {
  return getProviders().find(p => p.name === name) || null
}

// ── Token cap management ───────────────────────────────────────

function getCaps () {
  return readConfig().caps || {}
}

function setCap (providerName, dailyLimit) {
  const config = readConfig()
  if (!config.caps) config.caps = {}
  config.caps[providerName] = {
    daily_limit: dailyLimit,
    updated_at: new Date().toISOString()
  }
  writeConfig(config)
}

function removeCap (providerName) {
  const config = readConfig()
  if (config.caps) delete config.caps[providerName]
  writeConfig(config)
}

function getCap (providerName) {
  const caps = getCaps()
  return caps[providerName] || null
}

// ── Sequence management ────────────────────────────────────────

function getSequences () {
  return readConfig().sequences || {}
}

function setSequence (contextType, providerNames) {
  const config = readConfig()
  if (!config.sequences) config.sequences = {}
  config.sequences[contextType] = providerNames
  writeConfig(config)
}

function removeSequence (contextType) {
  const config = readConfig()
  if (config.sequences) delete config.sequences[contextType]
  writeConfig(config)
}

function getSequence (contextType) {
  const sequences = getSequences()
  return sequences[contextType] || null
}

// ── Env key management ─────────────────────────────────────────

function setEnvKey (key, value) {
  ensureHomeDir()
  let content = ''
  if (fs.existsSync(ENV_FILE)) {
    content = fs.readFileSync(ENV_FILE, 'utf8')
  }

  const lines  = content.split('\n')
  const idx    = lines.findIndex(l => l.startsWith(`${key}=`))
  const newLine = `${key}=${value}`

  if (idx >= 0) {
    lines[idx] = newLine
  } else {
    lines.push(newLine)
  }

  fs.writeFileSync(ENV_FILE, lines.filter(l => l !== undefined).join('\n') + '\n')

  // Also update process.env for this session
  process.env[key] = value
}

function getEnvKey (key) {
  if (process.env[key]) return process.env[key]

  if (!fs.existsSync(ENV_FILE)) return null

  const content = fs.readFileSync(ENV_FILE, 'utf8')
  const line    = content.split('\n').find(l => l.startsWith(`${key}=`))
  if (!line) return null

  return line.split('=').slice(1).join('=').trim() || null
}

function loadEnv () {
  if (!fs.existsSync(ENV_FILE)) return
  const content = fs.readFileSync(ENV_FILE, 'utf8')
  for (const line of content.split('\n')) {
    if (!line || line.startsWith('#')) continue
    const [key, ...rest] = line.split('=')
    if (key && rest.length) process.env[key.trim()] = rest.join('=').trim()
  }
}

// ── Path exports ───────────────────────────────────────────────

module.exports = {
  HOME_DIR,
  CONFIG_FILE,
  ENV_FILE,
  DB_FILE,
  LOGS_DIR,
  GRAPHS_DIR,
  VENV_DIR,
  ensureHomeDir,
  readConfig,
  writeConfig,
  getProviders,
  addProvider,
  removeProvider,
  getProvider,
  getCaps,
  setCap,
  removeCap,
  getCap,
  getSequences,
  setSequence,
  removeSequence,
  getSequence,
  setEnvKey,
  getEnvKey,
  loadEnv
}
